### ISSUE TITLE
Active menu items are not as visible as they should

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#297]
Although the image overlay from the Hero of the Galaxy has the same settings as before the latest updates to Rosa2/Nova and Style Manager, the menu items seem to be less visible. See below:
![CleanShot 2021-07-27 at 17 23 09](https://user-images.githubusercontent.com/53944294/127173460-06abf9f1-2278-4530-9906-de1dfcc81b0d.png)

The same behaviour is present on websites of our customers where the biggest issue is regarding the Active Menu Item. Although the color of the Active Menu Item is the same as before the update, the text is barely visible now.

Here are some examples:

FlairScent
![CleanShot 2021-07-27 at 17 37 13](https://user-images.githubusercontent.com/53944294/127173898-3b7dbc26-a457-4885-850b-7a8f24ef2ea5.png)

Centrul DigitalEdu (almost not visible at all)
![CleanShot 2021-07-27 at 17 39 28](https://user-images.githubusercontent.com/53944294/127174002-4b9c63fb-7475-43df-aa55-d1a2cb36f290.png)

**Comment by madalingorbanescu** [comment]
We were applying a gradient on the first Hero Block on the page. After the latest update, that gradient was not visible anymore, because it was using `--theme-header-height` variable, which is not available anymore. I have made a few adjustments and I am using another variable which should approximately match header height.

Solved in 11b722f823bfd5b5e1b7dd13ca600d5e1a0d7040
